version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/var/www
    environment:
      - ISSUE_DB_HOST=db
      - ISSUE_DB_PORT=5432
      - ISSUE_DB_NAME=chirper
      - ISSUE_DB_USER=postgres
      - ISSUE_DB_PASSWORD=postgres
    ports:
      - "3000:80"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chirper
    ports:
      - "5000:5432"