version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_ENGINE=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=chirper
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3001:80"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chirper
    ports:
      - "5000:5432"
  frontend:
    build:
      context: ./app
    ports:
        - "3000:8080"
  selenium-hub:
    image: selenium/hub:3.14.0-dubnium
    container_name: selenium-hub
    ports:
    - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14.0-dubnium
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444