version: '3'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_ENGINE=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=chirper
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3001:80"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chirper
    ports:
      - "5000:5432"
  frontend:
    build:
      context: ./app
    ports:
        - "3000:8080"