version: '2'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/var/www
    environment:
      - DB_ENGINE=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=chirper
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3001:80"
    networks:
      chirper:
        aliases:
          - api.chirper.com
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chirper
    ports:
      - "5000:5432"
    networks:
      - chirper
  frontend:
    build:
      context: ./app
    ports:
      - "80:8080"
    networks:
      chirper:
        aliases:
        - local.chirper.com

networks:
  chirper: